#!/bin/bash

#   Copy to /usr/bin and don't forget to make the script executable
#   Usage: setjv11

sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
JAVA_HOME_LOCAL="/usr/lib/jvm/java-11-openjdk-amd64/"
sudo sed -i '/^JAVA_HOME/d' /etc/environment
echo "JAVA_HOME=${JAVA_HOME_LOCAL}" | sudo tee -a /etc/environment > /dev/null
source /etc/environment
