#!/bin/bash

#   Copy to /usr/bin and don't forget to make the script executable
#   Usage: pull-unrelated <url> (or origin if not specified)

REPO_URL=$1

if [ -z "$REPO_URL" ]
then
    REPO_URL="origin"
fi

git pull ${REPO_URL} master --allow-unrelated-histories