#!/bin/bash
#   Create git commit with random emoji (but add all uncommited files before)
#   Usage: rnd-commit

#   Copy to /usr/bin and don't forget to make the script executable
EMOJIS=(😺 😸 😹 😻 😼 😽 🙀 😿 😾 😂 😂 😝 😁 😱 👉 🙌 🍻 🔥 🌈 ☀ 🎈 🌹 💄 🎀 ⚽ 🎾 🏁 😡 👿 🐻 🐶 🐬 🐟 🍀 👀 🚗 🍎 💝 💙 👌 ❤ 😍 😉 😓 😳 💪 💩 🍸 🔑 💖 🌟 🎉 🌺 🎶 👠 🏈 ⚾ 🏆 👽 💀 🐵 🐮 🐩 🐎 💣 👃 👂 🍓 💘 💜 👊 💋 😘 😜 😵 🙏 👋 🚽 💃 💎 🚀 🌙 🎁 ⛄ 🌊 ⛵ 🏀 🎱 💰 👶 👸 🐰 🐷 🐍 🐫 🔫 👄 🚲 🍉 💛 💚)

RANDOM_EMOJI() {
  SELECTED_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]};
  echo $SELECTED_EMOJI;
}

COMMIT_EMOJI=$(RANDOM_EMOJI)

git add .
git commit -m "${COMMIT_EMOJI}"