#!/bin/bash
#   Force update vscode to the latest version

#   Copy to /usr/bin and don't forget to make the script executable
wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb
sudo dpkg -i /tmp/code_latest_amd64.deb